"""add_cascade_delete_to_weather_records

Revision ID: 0665f5c9b8c2
Revises: 3b11e84c05de
Create Date: 2025-12-11 10:08:24.966704

"""

from typing import Sequence, Union

import geoalchemy2
import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0665f5c9b8c2"
down_revision: Union[str, Sequence[str], None] = "3b11e84c05de"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("weatherrecord_photo_id_fkey"), "weatherrecord", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "weatherrecord", "summitphoto", ["photo_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "weatherrecord", type_="foreignkey")
    op.create_foreign_key(
        op.f("weatherrecord_photo_id_fkey"),
        "weatherrecord",
        "summitphoto",
        ["photo_id"],
        ["id"],
    )
    # ### end Alembic commands ###
