"""add is_private column to users

Revision ID: 08c1b1853172
Revises: 550ad850569d
Create Date: 2025-12-01 07:44:52.691122

"""

from typing import Sequence, Union

import geoalchemy2
import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "08c1b1853172"
down_revision: Union[str, Sequence[str], None] = "550ad850569d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "is_private", sa.Boolean(), nullable=False, server_default=sa.false()
        ),
    )
    op.alter_column("user", "is_private", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "is_private")
    # ### end Alembic commands ###
