"""create moutain range table

Revision ID: 1b824668f6a7
Revises: c4178a38eb6c
Create Date: 2025-11-17 13:31:20.643349

"""

from typing import Sequence, Union

import geoalchemy2
import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1b824668f6a7"
down_revision: Union[str, Sequence[str], None] = "c4178a38eb6c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mountainrange",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("peak", sa.Column("mountain_range_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "peak", "mountainrange", ["mountain_range_id"], ["id"])
    op.drop_column("peak", "range")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "peak", sa.Column("range", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.drop_constraint(None, "peak", type_="foreignkey")
    op.drop_column("peak", "mountain_range_id")
    op.drop_table("mountainrange")
    # ### end Alembic commands ###
