"""added wiki page to peak

Revision ID: 1be80989d027
Revises: 5f9490f46e97
Create Date: 2025-11-18 11:41:32.772062

"""

from typing import Sequence, Union

import geoalchemy2
import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1be80989d027"
down_revision: Union[str, Sequence[str], None] = "5f9490f46e97"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "peak",
        sa.Column("wiki_page", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("peak", "wiki_page")
    # ### end Alembic commands ###
