"""make fields in weatherrecords optional

Revision ID: 3b11e84c05de
Revises: e1845fff72fd
Create Date: 2025-12-11 09:51:49.526361

"""

from typing import Sequence, Union

import geoalchemy2
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3b11e84c05de"
down_revision: Union[str, Sequence[str], None] = "e1845fff72fd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "weatherrecord", "sunrise", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.alter_column(
        "weatherrecord", "sunset", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.alter_column(
        "weatherrecord",
        "temp",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.alter_column(
        "weatherrecord",
        "feels_like",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.alter_column(
        "weatherrecord",
        "dew_point",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.alter_column(
        "weatherrecord", "pressure", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "weatherrecord", "humidity", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "weatherrecord", "clouds", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "weatherrecord", "visibility", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "weatherrecord",
        "wind_speed",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.alter_column(
        "weatherrecord", "wind_deg", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "weatherrecord",
        "rain",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.alter_column(
        "weatherrecord",
        "snow",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "weatherrecord",
        "snow",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        "weatherrecord",
        "rain",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        "weatherrecord", "wind_deg", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "weatherrecord",
        "wind_speed",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        "weatherrecord", "visibility", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "weatherrecord", "clouds", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "weatherrecord", "humidity", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "weatherrecord", "pressure", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "weatherrecord",
        "dew_point",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        "weatherrecord",
        "feels_like",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        "weatherrecord",
        "temp",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        "weatherrecord", "sunset", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.alter_column(
        "weatherrecord", "sunrise", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    # ### end Alembic commands ###
