"""rename altitude column to abbreviation

Revision ID: 49510f16767a
Revises: 091fc4e7e9c7
Create Date: 2025-11-21 09:32:04.587164

"""

from typing import Sequence, Union

import geoalchemy2
import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "49510f16767a"
down_revision: Union[str, Sequence[str], None] = "091fc4e7e9c7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("summitphoto", "altitude", new_column_name="alt")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("summitphoto", "alt", new_column_name="altitude")
    # ### end Alembic commands ###
