"""added constraint on peaks and mountain ranges names

Revision ID: 5f9490f46e97
Revises: 1b824668f6a7
Create Date: 2025-11-18 09:32:45.010692

"""

from typing import Sequence, Union

import geoalchemy2
import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5f9490f46e97"
down_revision: Union[str, Sequence[str], None] = "1b824668f6a7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_mountainrange_name"), "mountainrange", ["name"], unique=True
    )
    op.create_unique_constraint(
        "uq_peak_name_elevation_mountain_range",
        "peak",
        ["name", "elevation", "mountain_range_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_peak_name_elevation_mountain_range", "peak", type_="unique")
    op.drop_index(op.f("ix_mountainrange_name"), table_name="mountainrange")
    # ### end Alembic commands ###
