"""add created_at to all models

Revision ID: 832c2d78a053
Revises: 27b1a71e5353
Create Date: 2025-12-11 12:38:30.674515

"""

from typing import Sequence, Union

import geoalchemy2
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "832c2d78a053"
down_revision: Union[str, Sequence[str], None] = "27b1a71e5353"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "mountainrange", sa.Column("created_at", sa.DateTime(), nullable=False)
    )
    op.add_column("summitphoto", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.drop_column("summitphoto", "uploaded_at")
    op.add_column(
        "weathercondition", sa.Column("created_at", sa.DateTime(), nullable=False)
    )
    op.add_column(
        "weatherrecord", sa.Column("created_at", sa.DateTime(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("weatherrecord", "created_at")
    op.drop_column("weathercondition", "created_at")
    op.add_column(
        "summitphoto",
        sa.Column(
            "uploaded_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("summitphoto", "created_at")
    op.drop_column("mountainrange", "created_at")
    # ### end Alembic commands ###
