"""add weather_record to weather_condition link

Revision ID: 852c8a7370fa
Revises: 8987905a84c8
Create Date: 2025-12-09 14:10:33.890557

"""

from typing import Sequence, Union

import geoalchemy2
import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "852c8a7370fa"
down_revision: Union[str, Sequence[str], None] = "8987905a84c8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "weatherrecordweatherconditionlink",
        sa.Column("record_id", sa.Integer(), nullable=False),
        sa.Column("condition_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["condition_id"],
            ["weathercondition.id"],
        ),
        sa.ForeignKeyConstraint(
            ["record_id"],
            ["weatherrecord.id"],
        ),
        sa.PrimaryKeyConstraint("record_id", "condition_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("weatherrecordweatherconditionlink")
    # ### end Alembic commands ###
