"""create weatherrecord and weathercondition tables

Revision ID: 8987905a84c8
Revises: 08c1b1853172
Create Date: 2025-12-09 08:43:59.627322

"""

from typing import Sequence, Union

import geoalchemy2
import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8987905a84c8"
down_revision: Union[str, Sequence[str], None] = "08c1b1853172"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "weathercondition",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("main", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("icon", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "weatherrecord",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("photo_id", sa.Integer(), nullable=False),
        sa.Column("sunrise", sa.DateTime(), nullable=False),
        sa.Column("sunset", sa.DateTime(), nullable=False),
        sa.Column("temp", sa.Float(), nullable=False),
        sa.Column("feels_like", sa.Float(), nullable=False),
        sa.Column("dew_point", sa.Float(), nullable=False),
        sa.Column("pressure", sa.Integer(), nullable=False),
        sa.Column("humidity", sa.Integer(), nullable=False),
        sa.Column("clouds", sa.Integer(), nullable=False),
        sa.Column("visibility", sa.Integer(), nullable=False),
        sa.Column("wind_speed", sa.Float(), nullable=False),
        sa.Column("wind_deg", sa.Integer(), nullable=False),
        sa.Column("rain", sa.Float(), nullable=False),
        sa.Column("snow", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["photo_id"],
            ["summitphoto.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("weatherrecord")
    op.drop_table("weathercondition")
    # ### end Alembic commands ###
