"""added username_display column

Revision ID: 9aff137c78eb
Revises: 49510f16767a
Create Date: 2025-11-26 12:31:13.363353

"""

from typing import Sequence, Union

import geoalchemy2
import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9aff137c78eb"
down_revision: Union[str, Sequence[str], None] = "49510f16767a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("username_display", sqlmodel.sql.sqltypes.AutoString()),
    )

    op.execute(
        """
        UPDATE "user"
        SET username_display = username
    """
    )

    op.alter_column("user", "username_display", nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "username_display")
    # ### end Alembic commands ###
