"""add api_id field to weather_condition

Revision ID: e1845fff72fd
Revises: 852c8a7370fa
Create Date: 2025-12-11 09:48:15.812056

"""

from typing import Sequence, Union

import geoalchemy2
import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e1845fff72fd"
down_revision: Union[str, Sequence[str], None] = "852c8a7370fa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("weathercondition", sa.Column("api_id", sa.Integer(), nullable=False))
    op.create_index(
        op.f("ix_weathercondition_api_id"), "weathercondition", ["api_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_weathercondition_api_id"), table_name="weathercondition")
    op.drop_column("weathercondition", "api_id")
    # ### end Alembic commands ###
